---
title: "Causal inference and co-evolutionary contingencies using dynamic phylogenetic models"
format: html
editor: visual
bibliography: references.bib
---

## Introduction

Phylogenetic comparative methods (PCMs) are commonly used to study the co-evolution of organismal traits, spanning topics such as anatomy and physiology [@garland2005phylogenetic; @oconnor2022immunity; @thayer2018impact; @navalon2019evolutionary; @dunn2015evolutionary], life history and behavior [@maclean2012does; @clayton1994comparative; @salguero2016fast; @bielby2007fast; @cornwallis2017cooperation; @wilkinson2019recurrent], and cultural evolution [@mace2005phylogenetic; @watts2015broad; @navarrete2016coevolution]. "Co-evolution" refers to repeatable patterns of trait co-variation over evolutionary time, across species or across populations. In practice, co-evolution can be investigated using a diverse family of statistical techniques, depending on the research question and type of data available [@harvey1991comparative; @garamszegi2014modern; @nunn2011comparative].

Trait co-evolution simply describes *how* traits change over time. Such descriptions have value for understanding natural history, ancestral state reconstruction (using the present to retrodict the past), and can stimulate new research questions. However, simply inferring that traits changed together in the past does not tell us *why* they changed, or how the traits would respond to intervention, i.e., causality. Nonetheless, researchers in ecology and evolution are often motivated to study trait co-evolution because they believe these patterns reflect causal relations. We briefly review some popular classes of PCM and their limitations with respect to causal inference.

## "Static" PCMs

Static PCMs quantify co-evolution between traits using the evolutionary regression or correlation coefficient [@pagel1993seeking]. The evolutionary regression coefficient is an undirected association between traits over evolutionary time is $b = \frac{\sigma(X,Y)}{\sigma^2(X)}$, and the evolutionary correlation coefficient is the standardized coefficient $\rho = \frac{\sigma(X,Y)}{\sigma(X)\sigma(Y)}$ which can be interpreted as "a one standard deviation increase in trait $X$ is associated with a $\rho$ standard deviation change in trait $Y$."

#### When can be interpret the evolutionary regression as a causal effect?

```{r, message=FALSE, warning=FALSE}
require(rethinking)
require(dagitty)

phy_no_confound <- dagitty( "dag {
                            PHY -> Y
                            X -> Y
                            }")

phy_confound <- dagitty( "dag {
                            PHY -> Y
                            PHY -> X
                            X -> Y
                            }")
  
par(mfrow=c(1,2))
drawdag(phy_no_confound)
drawdag(phy_confound)
  
```
To understand when the evolutionary regression coefficient can be interpreted as a causal effect, we must first clarify what "causality" means. Following Pearl (some citations), we say that $X$ is a cause of $Y$ when $Pr(Y|do(X = x)) \neq Pr(Y|do(X = \textrm{not x}))$. The do() operator represents an *intervention* in which the value of some variable is fixed (for example, through assignment in a randomized experiment). If the probability distribution of $Y$ changes based on the value of $X$ that is assigned, then $X$ has a causal effect on $Y$. Note here that $X$ refers to a random variable while $x$ refers to some unit value of that variable.

### Phylogenetic Generalized Least Squares (PGLS)

Phylogenetic generalized least squares (PGLS) is a variant of linear regression that accounts for the covariance between species or populations due to shared evolutionary history (likewise for its predecessor, independent contrasts) [@grafen1989phylogenetic; @symonds2014primer; @blomberg2012independent]. Given some outcome $Y$ and a co-evolutionary predictor $X$, an observation $i$ from species or population $j$ is modeled as:

$$y_{ij} = \beta_0 + \beta_xx_{ij} + \epsilon_{ij}$$
$$ \epsilon \sim  \mathcal{N}(0, \boldsymbol{\Sigma})$$
$$\boldsymbol{\Sigma} = \sigma^2\boldsymbol{V} $$
Where $\mathcal{N}$ denotes a normal or Gaussian probability density function and $\sigma^2$ is the variance of $Y$ conditional on $X$. $\beta_x$ is an estimator of the evolutionary regression coefficient that takes into account the phylogenetic non-independence between tip species. The covariance between related species is proportional to the off-diagonals of the phylogenetic variance-covariance matrix $\boldsymbol{V}$. To construct $\boldsymbol{V}$, we need (1) a matrix of patristic distances between species (i.e., time since divergence from last common ancestor) and (2) an assumed model of trait evolution.

The most commonly assumed model is Brownian motion (also called the Wiener process and thus denoted $W$), where $W$ follows a random walk proportional to time ($T$), such that, for any time $t$:

$$ W_{T= t} - W_{T = 0} \sim\mathcal{N}(0,\sigma t) $$
Therefore, the variance for a given species or population $j$ is proportional to total branch length of the tree leading from root to tip, and the covariance between $j$ and any other species or population $k$ is proportional to their amount of shared history. For example, imagine a phylogeny with only $J$ = 3 tip species. The last common ancestor of all species is dated to T = 10,000 years ago, and the last common ancestor of 2 and 3 is dated to 0.5T = 5,000 years ago. The implied phylogenetic variance-covariance matrix ($\boldsymbol{V}$) under a Brownian motion model is thus:

$$ \boldsymbol{V} = \sigma^2 \begin{bmatrix}
T, & 0, & 0 \\
0, & T, & 0.5T \\
0, & 0.5T, & T
\end{bmatrix} $$

Thus, the total variance for species 3 is the sum of its evolutionary history, $\sigma^2[t(2,3)] + \sigma^2[t(3) - t(2,3)]$ and the covariance between species 2 and 3 is equal to the sum of their *shared* evolutionary history $\sigma^2[t(2,3)]$ (the tree time for their most recent common ancestor), which is always some fraction of the species total evolutionary time $T_j$. If the tree is ultrametric (all tips equidistant from the root), $T_j$ = $T ~\forall ~j \in J$. 

$\sigma$ is easier to interpret when we first scale all times by the total tree length $T$. We will denote such a scaled variance-covariance matrix as $\boldsymbol{V}_s$:

$$ \boldsymbol{V}_s = \frac{\boldsymbol{V}}{T} = \sigma^2 \begin{bmatrix}
1, & 0, & 0 \\
0, & 1, & 0.5 \\
0, & 0.5, & 1
\end{bmatrix} $$

Empirically, the actual degree of covariance between related species or populations may be less than expected under a pure Brownian motion model. For example, when evolution is rapid (or more mundanely, when measurement error on trait data is substantial) the "phylogenetic signal" will be weak such that even closely related taxa may have dramatically different trait values [@blomberg2003testing; @kamilar2013phylogenetic]. PGLS can estimate the strength of phylogenetic signal from comparative data, multiplying the off-diagonals of the variance-covariance matrix by $\lambda \in [0,1]$ [@pagel1999inferring]. For example:

$$ \boldsymbol{V_s} = \sigma^2 \begin{bmatrix}
1, & 0, & 0 \\
0, & 1, & \lambda0.5 \\
0, & \lambda0.5, & 1
\end{bmatrix} $$

This scaling is often referred to a≠s a "branch length transformation," because shrinking the off-diagonals (shared evolutionary history) while holding the diagonals constant (independent evolution) is equivalent to "stretching" the terminal branches leading to the tips and "shrinking" the past co-evolutionary branches. $\lambda = 1$ indicates that the phylogenetic strength is as strong as expected under a Brownian motion model, while lower values means that a lower proportion of the trait variance can be attributed to shared evolutionary history. At the extreme of $\lambda = 0$, $\boldsymbol{V}_s$ becomes an identity matrix and PGLS reduces to standard least squares regression.

Brownian motion is the simplest and most widely used model, and often interpreted as "drift" across the phylogenetic tree. Other popular choices include Ornstein-Uhlenbeck, where change due is due to both random drift and "stabilizing selection" towards some optimal trait value, and Early Burst models of adaptive radiation where the rate of change ($\sigma$) decreases over time. In general, $\boldsymbol{V}$ is constructed by inputting a matrix of phylogenetic distances to some covariance function $C(x,x')$ such that $V_{[j,k]} = C(j,k)$.

Although PGLS is widely used in comparative biology, it has key limitations such as: assumption of Gaussian errors, prone to overfitting due to lack of parameter regularization, and cannot accommodate many common data structures including repeated measures of species trait values, missing data, and measurement error. In the next section we review more flexible regression approaches, as well as an important alternative method of estimating evolutionary associations.

### Phylogenetic Generalized Multilevel Models

Phylogenetic generalized multilevel models (PGLMMs) extend the study of trait coevolution, leveraging analytic strategies developed in quantitative genetics to accommodate more complex, multivariate model designs with non-Gaussian outcomes [@hadfield2010general; @ives2010phylogenetic; @ives2011generalized]. Rather than explicitly scaling the off-diagonals of $\boldsymbol{V}_s$ with some parameter $\lambda$, phylogenetic signal is quantified as the ratio of the variance of phylogenetic random effects $\nu$ (also called 'mixed' and 'varying' effects) to total trait variance. For example, an observation of a Gaussian trait $Y$ from a species or population $j$ and predictor $X$ is modeled as:

$$ y_{i,j} = \beta_0 + \beta_{x} x_{ij} + \nu_{j} + \epsilon_{ij} \\$$
$$ \nu \sim \mathcal{N}(0,\boldsymbol{\Sigma}_{\nu}) \\$$
$$\epsilon_{ij} \sim \mathcal{N}(0,\boldsymbol{\Sigma}_{\epsilon}) \\$$
$$\boldsymbol{\Sigma}_{\nu} = \sigma^2_{\nu}\boldsymbol{V}_s \\$$
$$\boldsymbol{\Sigma}_{\epsilon} = \sigma^2_{\epsilon}\boldsymbol{I} \\$$

Where $\boldsymbol{I}$ is an identity matrix and thus the residuals $\epsilon$ are assumed conditionally independent. The "phylogenetic signal" is now estimated as $\lambda_{\textrm{PGLMM}} = \frac{\sigma_{\nu}^2}{\sigma_{\nu}^2 + \sigma_{\epsilon}^2}$ (adjusted for $X$) and equivalent to $\lambda_{\textrm{PGLS}}$, but with the greater flexibility afforded by PGLMMs. $\lambda_{\textrm{PGLMM}}$ is also sometimes referred to as "phylogenetic heritability" [@hadfield2010general].

In this model, $\beta_{x(\textrm{PGLMM})}$ has the same interpretation as $\beta_{x(\textrm{PGLS})}$. If the response was non-Gaussian, $\beta_{x(\textrm{PGLS})}$ has the same interpretation *on the latent scale*. Conversion of the phylogenetic regression coefficient $\beta_{x(\textrm{PGLMM})}$ to the observation scale requires inverting the link function, and will be sensitive to other model parameters.

#### Phylogenetic Path Analysis & Causal Inference




While the terminology is not always consistent in the literature, note that "phylogenetic correlation" refers to a . A residual correlation refers to the remaining trait covariance *after* accounting for similarity due to shared evolutionary history. The residual correlations derived from PCMs are often interpreted as evidence for convergent evolution, adjusted for statistical non-independence and confounding due to phylogeny.

Independent contrasts, PGLS, PGLMMs, PPA


Discrete data can be modeled in the GLMMM framework if we conceptualize discrete phenotypes (binary, ordinal, categorical) as manifestations of a latent continuous trait, as in the quantitative genetic threshold model [@wright1934; @felsenstein2005using].


## "Dynamic" PCMs

Pagel's discrete, Hidden Markov Models, Butler & King OU

can be identified statistically as non-zero between-trait phylogenetic correlations----or any other measure of mutual information over evolutionary time.

THREE SCENARIOS TO SIMULATE:

\(1\) Confounding by third variable X_3 -\> X_2, X_3 -\> X_1

\(2\) Correlated drift (CoV\[X_1,X_2\]) != 0)

\(3\) Including correlated drift (shrinking cross-effects)
